# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

export ZSH_CUSTOM=~/.custom-zsh

# Install theme
ZSH_THEME="dracula"
DRACULA_ARROW_ICON="（っ＾▿＾）"

# Allow oh-my-zsh to automatically update
DISABLE_UPDATE_PROMPT=true

# Make completion consider case
CASE_SENSITIVE="true"

# Enable plugins. The format in plugins=(plugin1 plugin2 ...)
# - command-not-found: Provides useful msg on install command on ubuntu
# - npm: Provides auto-complete for NPM commands
plugins=(command-not-found npm)

# Start oh-my-zsh...
source $ZSH/oh-my-zsh.sh

# Load private dotfiles if they exist
PRIV_ZSHRC="${HOME}/Projects/Tools/private-dotfiles/assets/private.zshrc"
if [[ -r $PRIV_ZSHRC ]]; then
    source $PRIV_ZSHRC
fi

# Load corp dotfiles if they exist
CORP_ZSHRC="${HOME}/Projects/Tools/corp-dotfiles/assets/corp.zshrc"
if [[ -r $CORP_ZSHRC ]]; then
    source $CORP_ZSHRC
fi

# Load dotfiles
source "${HOME}/Projects/Tools/dotfiles/terminal/source"
